name: publish 🚀

on: push
jobs:
  build:
    runs-on: ubuntu-latest  # Correct indentation
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

   steps:
   - uses: actions/checkout@v3

   -name: Setup .NET
   uses: actions/setup-dotnet@v3
   with:
     dotnet-version: '6.0.x'

     - name: Restore
       run: dotnet restore ./CurrentTimeService.sln

       -name: Build
        run: dotnet build ./CurrentTimeService.sln --configuration release --no-restore

        -name: Publish
        run: dotnet publish ./CurrentTimeService.sln --configuration Release --no-build
